[versions]
activityKtx = "1.12.2"
agp = "8.13.2"
healthconnect = "1.1.0"
preferenceKtx = "1.2.1"
spongycastle = "1.58.0.0"
coreKtx = "1.17.0"
junitBom = "6.0.2"
kotlin = "2.3.0"
material = "1.13.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-healthconnect-client = { module = "androidx.health.connect:connect-client", version.ref = "healthconnect" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
spongycastle-core = { module = "com.madgag.spongycastle:core", version.ref = "spongycastle" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

